### ISSUE TITLE
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.

### ISSUE THREAD

**Issue by jamabaiz** [john-bartu/powtorki-online-api#3]
```
Traceback (most recent call last):
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/routers/knowledge.py", line 114, in get_knowledge_item
    page = ItemLister(db, model, subject).get_item(page_id)
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/crud/item_lister.py", line 41, in get_item
    item.document = page_renderer(item.document).strip()
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/render/renderer.py", line 125, in page_renderer
    resp = re.sub(pattern, lambda m: func(m.group(1)), resp)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/render/renderer.py", line 125, in <lambda>
    resp = re.sub(pattern, lambda m: func(m.group(1)), resp)
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/render/renderer.py", line 52, in func
    res = find_image_slug(value)
  File "/usr/home/bartu-m/powtorkionline_fastapi/./app/render/renderer.py", line 23, in find_image_slug
    return session.query(Media).filter(Media.slug == media_slug).all()
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1798, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 645, in _revalidate_connection
    self._invalid_transaction()
  File "/usr/home/bartu-m/.virtualenvs/fastapi3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 617, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
````

**Comment by jamabaiz** [comment]
Fix in #4
